In [5]:
import pandas as pd

In [6]:
df_titles = pd.read_csv('titles.csv')

In [7]:
df_titles['index'] = df_titles.index

In [32]:
df_titles.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,index
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",6229
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",6230
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,6231
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",6232
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,6233

In [9]:
df_links = pd.read_json('links.json')

In [27]:
links = {}

In [28]:
for row, value in df_links.iterrows():
    
    if value.source in links:
        links[value.source]["target"].append({'target': value.target, 'weight': value.weight})
    else:
        links[value.source] = {
            "targets": {
                
            },
        }

In [45]:
df_titles['links'] = df_titles['index'].apply(lambda x: links[x] if x in links else None)

In [47]:
df_titles.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,index,links
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",6229,"{'targets': [{'target': 3864.0, 'weight': 0.71..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",6230,"{'targets': [{'target': 4575.0, 'weight': 0.63..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,6231,"{'targets': [{'target': 5808.0, 'weight': 0.75..."
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",6232,"{'targets': [{'target': 6052.0, 'weight': 0.72..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,6233,"{'targets': [{'target': 5135.0, 'weight': 0.71..."